const data1 = [
	{
	  id: 1,
	  category: "DEVELOPMENT",
	  totalLike: "600",
	  title: "The services provide for design ",
	//   desc_one: "1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate distinctio assumenda explicabo veniam temporibus eligendi.",
	//   desc_two: "1 Consectetur adipisicing elit. Cupiditate distinctio assumenda. dolorum alias suscipit rerum maiores aliquam earum odit, nihil culpa quas iusto hic minus!",
	  image: "./images/img-9.jpg",
	},
	{
	  id: 2,
	  category: "APPLICATION",
	  totalLike: "750",
	  title: "Mobile app landing design & maintain",
	//   desc_one: "2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate distinctio assumenda explicabo veniam temporibus eligendi.",
	//   desc_two: "2 Consectetur adipisicing elit. Cupiditate distinctio assumenda. dolorum alias suscipit rerum maiores aliquam earum odit, nihil culpa quas iusto hic minus!",
	  image: "./images/bougie.png",
	},
	{
	  id: 3,
	  category: "PHOTOSHOP",
	  totalLike: "630",
	  title: "Logo design creativity & Application ",
	//   desc_one: "3 Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate distinctio assumenda explicabo veniam temporibus eligendi.",
	//   desc_two: "3 Consectetur adipisicing elit. Cupiditate distinctio assumenda. dolorum alias suscipit rerum maiores aliquam earum odit, nihil culpa quas iusto hic minus!",
	  image: "./images/img-6.jpg",
	},
	{
	  id: 4,
	  category: "FIGMA",
	  totalLike: "360",
	  title: "Mobile app landing design & Services",
	//   desc_one: "4 Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate distinctio assumenda explicabo veniam temporibus eligendi.",
	//   desc_two: "4 Consectetur adipisicing elit. Cupiditate distinctio assumenda. dolorum alias suscipit rerum maiores aliquam earum odit, nihil culpa quas iusto hic minus!",
	  image: "./images/img-3.jpg",
	},
	{
	  id: 5,
	  category: "WEB DESIGN",
	  totalLike: "280",
	  title: "Design for tecnology & services",
	//   desc_one: "5 Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate distinctio assumenda explicabo veniam temporibus eligendi.",
	//   desc_two: "5 Consectetur adipisicing elit. Cupiditate distinctio assumenda. dolorum alias suscipit rerum maiores aliquam earum odit, nihil culpa quas iusto hic minus!",
	  image: "./images/img-4.jpg",
	},
	{
	  id: 6,
	  category: "WEB DESIGN",
	  totalLike: "690",
	  title: "App for tecnology & services",
    //   desc_one: " 6 Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate distinctio assumenda explicabo veniam temporibus eligendi.",
	//   desc_two: "6 Consectetur adipisicing elit. Cupiditate distinctio assumenda. dolorum alias suscipit rerum maiores aliquam earum odit, nihil culpa quas iusto hic minus!",
	  image: "./images/img-8.jpg",
	},
  ]
  export default data1