export default [
	{ id: '1', imageName: 'amazon-web-services.png', tag: 'DevOps' },
	{ id: '2', imageName: 'docker.png', tag: 'DevOps' },
	{ id: '3', imageName: 'k8s.png', tag: 'DevOps' },
	{ id: '4', imageName: 'Git.png', tag: 'DevOps' },
	{ id: '5', imageName: 'Apache.png', tag: 'Webtech' },
	{ id: '6', imageName: 'Jenkins.png', tag: 'DevOps' },
	{ id: '7', imageName: 'Ansible.png', tag: 'DevOps' },
	{ id: '8', imageName: 'Terraform.png', tag: 'DevOps' },
	{ id: '9', imageName: 'microsoft-sql-server.png', tag: 'Database' },
	{ id: '10', imageName: 'Nginx.png', tag: 'Webtech' },
	{ id: '11', imageName: 'MySQL.png', tag: 'Database' },
	{ id: '12', imageName: 'postgresql.png', tag: 'Database' },
	{ id: '13', imageName: 'MongoDB.png', tag: 'Database' },
	{ id: '14', imageName: 'Prometheus.png', tag: 'Monitoring/Alerting' },
	{ id: '15', imageName: 'Grafana.png', tag: 'Monitoring/Alerting' },
	{ id: '16', imageName: 'Django.png', tag: 'Webtech' },
    { id: '17', imageName: 'React.png', tag: 'Webtech' },
    { id: '18', imageName: 'Python.png', tag: 'Code' },
    { id: '19', imageName: 'html5.png', tag: 'Code' },
];